language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

notifications:
    email: false

sudo: false

virtualenv:
    system_site_packages: true

install:
    - pip install weave

script:
    - python --version
    - PYTHON=python test_suite/test_all
