pages:
    script:
    - rm -rf public
    - mkdir public
    - cp -rT web public
    - rm -rf web
    - for name in `find . -type f`; do gzip -c "${name}" > "${name}.gz"; done
    artifacts:
        paths:
        - public

